application: album
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:

- url: /stylesheets
  static_dir: stylesheets

- url: /images
  static_dir: images

- url: /scripts
  static_dir: scripts

# Twitter Bootstrap
- url: /bootstrap
  static_dir: bootstrap

- url: /
  script: front.app  # handled by main.py

- url: /test
  script: test.app  # handled by main.py

- url: /.*
  script: main.app  # handled by main.py
  login: required

libraries:
- name: jinja2
  version: latest

- name: webapp2
  version: latest
