application: album
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:

- url: /stylesheets
  static_dir: stylesheets

- url: /images
  static_dir: images

- url: /scripts
  static_dir: scripts

# Twitter Bootstrap
- url: /bootstrap
  static_dir: bootstrap

# Handler for front page
- url: /
  script: front.app  # handled by front.py

- url: /.*
  script: main.app  # handled by main.py

libraries:
- name: jinja2
  version: latest
